### ISSUE TITLE
Search Data for valusation 감정평가

### ISSUE THREAD

**Issue by ras120** [kuj0210/Smart-mobile#15]
1.  valusation example
실제 감정평가 사례
http://www.mai.kr/upload/auction/2778fea3d40fad5b142ab463f08082c8.pdf?PHPSESSID=7b934d57414c285984e843ab318f586f

2. Detailed Evaluation Criteria for Appraisal Evaluation
감정평가 세부평가기준 - 한국감정원
실제 기관에서 감정평가를 실시하는 세부기준의 원문
주요부분 - 제4장 감정평가의 절차와 방법 : 감정평가의 순서와 기준, 종합 방법을 참고할 예정
     -제5장 물건별 감정평가, 제6장 목적별 감정평가 : 각 특징적인 상황, 기준에서의 평가를 참고할 예정

[감정평가 세부평가기준_원문-PDF.pdf](https://github.com/kuj0210/Regional-analyzer/files/1819046/_.-PDF.pdf)

3. NIMBY PIMFY 님비 핌피
NIMBY PIMFY data (Symptoms, causes and cases, etc.)
님비현상과 핌피현상이 정리된 자료 (유래, 증상, 원인과 사례 등) 
https://prezi.com/nulqo4rhe6gd/nimby-pimfy/

4. Simple Document
A summary of the valusation
감정평가에 대해 간단히 정리된 문서
http://contents.kocw.or.kr/document/lec/2012/Sangmyung/ShimJaeYoung/12.pdf

5. How to separate property valuation
부동산가치평가의 분리방법
이 내용의 주제를 보기보다 각 가치를 평가하는 내용을 참고
[부동산가치의 분리방법.PDF](https://github.com/kuj0210/Regional-analyzer/files/1819177/default.PDF)

6. Products with similar functionality
다방 - 지도 api를 통해 지정된 장소 주변의 시설들을 스캔하여 편의시설, 교통 항목을 평가하여 점수를 냄
 인근의 교육시설을 스캔해서 보여주는 기능
![image](https://user-images.githubusercontent.com/24354747/37523871-8ee582a8-296b-11e8-9645-525554a94489.png)

**Comment by kuj0210** [comment]
그 링크를 달고 아래내용을 간략하게 요약이나 필요데이터만 뽑아줘
