### ISSUE TITLE
유즈케이스 확립

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/Smart-mobile#18]
제공할 기능 및 필요센서 정리

**Comment by Kownby** [comment]
필요 기능
1.녹화된 음성, 음악(자장가 또는 백색소음) 출력.
2.주변 소음감지
3.온습도 감지
4.영 유아 촬영

더 할수 있다면.
1.미세먼지 농도 측정
2.아기 체온 측정
3.시선 측정(가능하다면)

**Comment by Kownby** [comment]
다양한 센서 판매 홈페이지

http://www.devicemart.co.kr/

**Comment by Kownby** [comment]
센서 사용방식중 온도 센서 사용방법

http://deneb21.tistory.com/207
