### ISSUE TITLE
file system for using speaker

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/Smart-mobile#21]
## 1. 스피커 제어 및 제어가능 종류(스피커 종류)
만약 스피커를 연결하고 그냥 재생만 하면 되는거라면 재생하는 방법까지

**Comment by ras120** [comment]
이따 정리

외장 메모리 마운트
https://wikidocs.net/7832
음악파일 재생
https://m.blog.naver.com/PostView.nhn?blogId=dlwjddns5&logNo=220740541961&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F

**Comment by ras120** [comment]
1. 재생방법
선행사항 
1.잭설정
http://blog.naver.com/PostView.nhn?blogId=chandong83&logNo=220732917839

sudo apt-get install raspi-config 후

![image](https://user-images.githubusercontent.com/24354747/37583916-d12a560c-2b96-11e8-8a84-a7a55feb0ee0.png)


2.pygame모듈 설치 
sudo apt-get install python-pygame

3.재생코드(python)

import pygame
import time

pygame.mixer.init() //초기화
sound = pygame.mixer.Sound("음원파일경로") //wav , ogg 호환
//반복, 타이머는 while, sleep 같은 함수로 작성필요
sound.play() //재생
sound.stop() //멈춤
![image](https://user-images.githubusercontent.com/24354747/37583509-04e798ee-2b95-11e8-9ff7-2fa1a5c15275.png)

**Comment by ras120** [comment]
2. 외부저장소의 음원재생은 해당경로만 알면 됨
외부저장소의 포멧호환 확인(NTFS사용)
sudo blkid 명령으로 연결장치 확인
/etc/fstab 파일 내용을 수정한다.
-예시 사진 맨아래 줄 추가
![image](https://user-images.githubusercontent.com/24354747/37584366-8954c572-2b98-11e8-8861-90be064832a1.png)
http://guzene.tistory.com/191

**Comment by kuj0210** [comment]
이슈로 정리좀부탁할게 좋은듯 천천히해도됨
