### ISSUE TITLE
발표계획서 제출

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/Smart-mobile#30]
일요일 20시 까지

"1 문제개요 ~ 1-나"             ::경원
"1-다 ~ 2-가-1 목표설정"    :: 해빈
"3설계제한요소 ~끝"           ::병윤

설계 계획서를 가지고 어떤식으로 발표를 진행할 건지 hwp 파일에 상세히 작성하여 
현재 이슈에 댓글로 파일달것.!

(어떤것을 중점으로 설명할것인지 발표때 어느그림을 보며, 또는 어떤 제스쳐를 취하며 진행할것인지 연극대본을 쓴다는 생각으로 상세히 작성)

**Comment by Kownby** [comment]
[대본_병윤.zip](https://github.com/kuj0210/Smart-mobile/files/1844968/_.zip)

**Comment by kuj0210** [comment]
pass 색상이 심리에 영향미치는 내용이 있으므로 편안한 녹색이나 쾌활한 노란색 이라고 걍 고것만 말해주면 더좋을듯

**Comment by HaebinKim** [comment]
[해빈_대본.zip](https://github.com/kuj0210/Smart-mobile/files/1845021/_.zip)

**Comment by ras120** [comment]
[대본_경원.zip](https://github.com/kuj0210/Smart-mobile/files/1845175/_.zip)

**Comment by kuj0210** [comment]
[피드백.zip](https://github.com/kuj0210/Smart-mobile/files/1845240/default.zip)
