### ISSUE TITLE
발표구상 내용종합 

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/Smart-mobile#41]
발표구상 내용종합  댓글로달것

**Comment by HaebinKim** [comment]
[발표구상_해빈.zip](https://github.com/kuj0210/Smart-mobile/files/1889452/_.zip)

**Comment by ras120** [comment]
[대본_경원.zip](https://github.com/kuj0210/Smart-mobile/files/1889469/_.zip)

**Comment by kuj0210** [comment]
[피드백.zip](https://github.com/kuj0210/Smart-mobile/files/1889813/default.zip)
