### ISSUE TITLE
음성 시스템

### ISSUE THREAD

**Issue by Kownby** [kuj0210/Smart-mobile#51]
일단 FFT를 사용하는 이유는 음성 파일은 시간에 따른 진폭인 **파형**을 보여준다. 샘플은 순수 울음소리로 아기의 목소리가 대부분이지만. 실제 녹화를 한다면 다른 소리(성인 남녀의 소리나 주변 물체의 소리 등)이 겹친다. 이걸 FFT를 이용하여 스팩트럼으로 바꾸면 특정 주파수(특정 물체 사람이 내는 진동)에 따른 진폭인 **스팩트럼** 을 알 수 있다. 

![k-103](https://user-images.githubusercontent.com/31425324/39663589-bf5c43ba-50b0-11e8-8b2a-2aa70a645bd4.png)
위 그림에서 
 - 빨간 사각형 부분이 파형(시간에 따른 진폭)
 - 파란 사격형 부분이 스팩트럼(주파수에 따른 진폭)
 - 푸리에 변환에 따른 결과이다.

이건 **현재 까지의 음성 디지털화 보고(진행중)** (https://github.com/kuj0210/Smart-mobile/issues/44) 의 녹색과 파란색 부분을 통 해 알수 있다. 그런데 fft는 시간에 따라 계속 FFT 변환으로 계속 바꿔야 하는데 저 내용을 이용하면 전체 샘플의 주파수에 따른 진폭만을 알 수 있다 이를 위해서 사용하는것이 **스팩트로그램(Spectrogram)** 이다.

## 스팩트로그램 
스팩트로그램이란 음성 신호를 주파수, 시간 , 진폭(강도) 로 분석하여 얻어지는 삼차원 적 그림으로 알 수 있다.

배고픔(2)
![spectrogram of 2 wav](https://user-images.githubusercontent.com/31425324/39663522-dd316402-50af-11e8-8de9-e07134fdec3f.png)

아픔(1)
![spectrogram of h1 wav](https://user-images.githubusercontent.com/31425324/39663523-dd855ecc-50af-11e8-8977-865d5df3ffe7.png)

졸림(2)
![spectrogram of s2 wav](https://user-images.githubusercontent.com/31425324/39663524-dddab606-50af-11e8-9d44-6799e1bf746d.png)

위 그림처럼 x축은 시간, y축은 주파수 색상 농도는 진폭으로 하여 스팩트럼(주파수에 따른 진폭) 과 파형(시간에 따른 진폭)을 둘 다 알수 있다.

이를 이용해서 시간에 따른 주파수(특정 울음소리 대역)의 진폭(크기,강도) 를 알 수 있게 된다.
이때또한 FFT알고리즘이 이용되며(코드의 라이브러리 설명내용.) 이로 우리가 찾고자 하는 내용을 찾을 수 있다.

**Comment by ras120** [comment]
import os
import wave
from matplotlib import pyplot as plt

wavfile = '3' + '.wav'

import pylab
def graph_spectrogram(wav_file):
    sound_info, frame_rate = get_wav_info(wav_file)
    pylab.figure(num=None, figsize=(19, 12))
    pylab.subplot(111)
    #pylab.title('spectrogram of %r' % wav_file)
    pylab.specgram(sound_info, Fs=frame_rate)
    #pylab.savefig('spectrogram of %r.png' % wav_file)

    ax1 = plt.subplot(211)
    Pxx, freqs, bins, im = plt.specgram(sound_info, Fs=frame_rate)


    print(len(Pxx))
    print(len(freqs))
    print(len(bins))
    print(len(Pxx[0]))

    tmp = []
    for j in range(len(bins)):
        k = 0
        for i in range(0, 20):
            if k < Pxx[i][j]:
                k = Pxx[i][j]
        tmp.append(k)

    count = 0
    len_count = 0
    sum_a = 0
    for i in range(len(tmp)):
        if tmp[i] > 1000:
            count += 1
            sum_a += tmp[i]
        if tmp[i] > 100:
            len_count += 1

    bindo = count / len_count
    aver = sum_a / count
    print(bindo, aver)

    if bindo > 0.6:                     
        print("울어욧!")

    if aver < 50000 and aver > 20000:   
        print("졸려요")
    elif aver > 50000:
        print("배고파요")
    elif aver < 20000:
        print("아파요")
    p3 = plt.plot(tmp, linewidth = 1, c = 'r')
    #plt.show()



def get_wav_info(wav_file):
    wav = wave.open(wav_file, 'r')
    frames = wav.readframes(-1)
    sound_info = pylab.fromstring(frames, 'int16')
    frame_rate = wav.getframerate()
    wav.close()
    return sound_info, frame_rate

graph_spectrogram(wavfile)

**Comment by kuj0210** [comment]
ㅇㅋ 낼까지 최대한 다듬고 우선 여기까지한걸로 ppt 만들게 ppt만들기용 자료 부탁함

**Comment by Kownby** [comment]
아이울음소리 라고 판단되는 특징값 범위 안에 들어가는 소리들의 빈도를 통해 아이가 우는 지 판단하고
우는 소리라고 판단될 경우 특징값들의 전체 평균을 구해 아이가 우는 소리의 타입을 찾아낸다.

구해서 실험한 각 샘플간의 환경이나 소리크기, 녹화상태, 녹화거리 등 오차가 많아 정확도가 떨어진다.

아래는 각 타입별 5개 샘플에 대한 결과
![image](https://user-images.githubusercontent.com/31425324/39673099-090f5b26-5171-11e8-99b9-7c7b231453a4.png)

**Comment by Kownby** [comment]
시간당 각 소리의 특징값들의 그래프 예시.

- 아픈 경우
![of h2 wav](https://user-images.githubusercontent.com/31425324/39673154-bbec4b00-5171-11e8-84fe-1d599aa300a3.png)

  - 배고픈 경우
![of 5 wav](https://user-images.githubusercontent.com/31425324/39673152-bb3d24cc-5171-11e8-84e0-4c944d659d20.png)


 - 졸린 경우
![of 5 wav](https://user-images.githubusercontent.com/31425324/39673153-bb9468fe-5171-11e8-89e9-aff903bd8b6e.png)
