### ISSUE TITLE
총괄스레드 변경

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/Smart-mobile#60]
월요일 23시까지

해빈 vi 클래스내부 작성 : vi는 사진한장 만들고 아무것도 하지 말것 사진만 만들것
경원 if클래스 내부 작성 : IF는 현재의 온습미세먼지 정보를 영수증처럼 하나의 문자열로 만들어서 print까지
[Push.zip](https://github.com/kuj0210/Smart-mobile/files/2042479/Push.zip)

**Comment by ras120** [comment]
Pi General Code 2.0에 Vo, Info 적용
